export { AboutTemplate } from './AboutTemplate'
export { BlogTemplate } from './BlogTemplate'
export { ContactUsTemplate } from './ContactUsTemplate'
export { HomeTemplate } from './HomeTemplate'
export { GalleryTemplate } from './GalleryTemplate'
export { OurMenuTemplate } from './OurMenuTemplate'
export { ReservationTemplate } from './ReservationTemplate'
export { ErrorTemplate } from './ErrorTemplate'
