export { Banner } from './Banner'
export { Footer } from './Footer'
export { Navbar } from './Navbar'
export { Dishes } from './Dishes'
export { ReservationForm } from './ReservationForm'
export { HeadingSection } from './HeadingSection'
