import Head from 'next/head'

import { Banner } from '@/shared/components'
import { MailUs, VisitUs } from './components'

export const ContactUsTemplate = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner title="Contact Us" />
        <MailUs />
        <VisitUs />
      </main>
    </>
  )
}
