import Head from 'next/head'

import { Banner, ReservationForm } from '@/shared/components'
import { Gallery, Reservation, Feature } from './components'

export const GalleryTemplate = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner title="Gallery" />
        <Gallery />
        <Reservation />
        <Feature />
        <ReservationForm />
      </main>
    </>
  )
}
