import { Banner } from '@/shared/components'
import Head from 'next/head'
import { AboutUs, Counts, Team } from './components'

export const AboutTemplate = () => {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner title="About" />
        <AboutUs />
        <Counts />
        <Team />
        {/* <Testimonial /> */}
      </main>
    </>
  )
}
