import Head from 'next/head'

import { Banner } from '@/shared/components'
import { E404 } from './components'

export const ErrorTemplate = () => {
  return (
    <>
      <Head>
        <title>404</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner title="404" />
        <E404 />
      </main>
    </>
  )
}
