import Head from 'next/head'

import {
  Carousel,
  Hero,
  Menu,
  TheStory,
  Blog,
  Reservation,
  Popular,
  Services
} from '@/shared/components'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <TheStory />
        <Menu />
        <Carousel />
        <Popular />
        <Services />
        <Blog />
        <Reservation />
      </main>
    </>
  )
}
