import { Banner } from '@/shared/components'
import Head from 'next/head'

export default function Reservation() {
  return (
    <>
      <Head>
        <title>Reservation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner title="Reservation" />
      </main>
    </>
  )
}
